### PR TITLE
UI to support multiple connection options

### PR DESCRIPTION
**Pull request by SvenAelterman**

### CODE REVIEW

**Review by softcraftsman — APPROVED** [review]
I've added the remaining images. Ready to be published.

**Comment by SvenAelterman** [comment]
@softcraftsman The build is failing because of some leftover, dead component reference. I will review it again and take care of it.

**Comment by SvenAelterman** [comment]
@softcraftsman By adding the change to the SWA config, you're probably also addressing #81

**Review by softcraftsman — APPROVED** [review]
Looks good.

**Pull request merged**
